Repository apache/maven-pmd-plugin, pull requests merged in 2025-06, with the labels that each got.

#214 Replace manually maintained release notes by link to GitHub
  src/site/markdown/releasenotes.md
  src/site/site.xml
Labels: enhancement

#227 Ignore the .vscode directory in git
  .gitignore
Labels: maintenance

#636 remove jira link
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip-changelog

#638 Documentation: Excludes should be placed in pluginManagement (#637)
  src/site/apt/examples/violation-exclusions.apt.vm
Labels: documentation

#640 Use constant 3.6.3 in prerequisites/maven as minimal Maven version
  pom.xml
Labels: enhancement
